### PR TITLE
Project-set-up:initial commit

### PR DESCRIPTION
**Pull request by yayaismaail**
Generate new rails app

### CODE REVIEW

**Review by rmiyoyo — APPROVED** [review]
## Hi @yayaismaail , 
**I haven't experienced any errors. I will go ahead and approve the PR.**
****Congratulations! 🎉****

## STATUS: APPROVED 🟢

**Comment by yayaismaail** [comment]
Hi @rmiyoyo 
A million thanks

**Comment by rmiyoyo** [comment]
Hi @Sami-Ullah-Tufail, @yayaismaail has just finished setting up everything. You can go ahead and pull the dev branch and start working on your tasks at your convenience. Great work @yayaismaail !

**Comment by Sami-Ullah-Tufail** [comment]
Yes let work

**Pull request merged**
